# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pflichtenheft.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from RequirementManagement import *

   
class PflichtenheftFenster(object):
    selectedProject = "a"

    # Thi Dok
    def __init__(self, selectedProject):
        self.selectedProject = selectedProject

    # Niki Dok
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800,900)
        #self.label = QtWidgets.QLabel(Dialog)
        #self.label.setGeometry(QtCore.QRect(50, 100, 61, 16))
        #self.label.setObjectName("Lastenheft")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 91, 16))
        self.label_2.setObjectName("Pflichtenheft")
        #self.listWidget = QtWidgets.QListWidget(Dialog)
        #self.listWidget.setGeometry(QtCore.QRect(50, 120, 400, 250))
        #self.listWidget.setObjectName("Lastenheft")

        #for cTuple in getAllRequirements(self.selectedProject):
        #    self.listWidget.addItems(cTuple)
            


        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setWordWrap(True)
        self.listWidget_2.setGeometry(QtCore.QRect(50, 120, 700, 730))
        self.listWidget_2.setObjectName("Pflichtenheft")


        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 101, 31))
        self.label_3.setObjectName("Projektname")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)    
        self.lineEdit.setGeometry(QtCore.QRect(50, 50, 400, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit Projektname")

        reqcount = int(1)
        for aTuple in getAllRequirements(self.selectedProject):
           tup1 = ''.join(aTuple)
           self.listWidget_2.addItem(str(reqcount) + ". Anforderung: ")
           self.listWidget_2.addItem(tup1)
           reqcount = int(reqcount) + int(1) 
           self.listWidget_2.addItem("")
           specIndex = 1
           for bTuple in getSpecificationText(tup1):     
              tup2 = "".join(bTuple) 
              #a = (str(specIndex) + ". Spezifikation: " + tup2,)
              
              #self.listWidget_2.addItems(a)
              self.listWidget_2.addItem(str(specIndex) + ". Spezifikation: ")
              self.listWidget_2.addItem(tup2)
              specIndex = int(specIndex) + 1
           self.listWidget_2.addItem("")
           self.listWidget_2.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    # Niki Dok
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pflichtenheft"))
        #self.label.setText(_translate("Dialog", "Lastenheft"))
        self.label_2.setText(_translate("Dialog", "Pflichtenheft"))
        self.label_3.setText(_translate("Dialog", "Projektname"))
        self.lineEdit.setPlaceholderText(_translate("AnforderungUndSpezifikation", "Projektname"))
        self.lineEdit.setEnabled(False)
        self.lineEdit.setText(self.selectedProject)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = PflichtenheftFenster()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
